"""Add new columns to PlanDocument

Revision ID: a9056ac0eb8a
Revises: 
Create Date: 2024-06-26 01:01:28.818068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9056ac0eb8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_of_plan', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payer', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('summarized_plan_coverage', sa.Text(), nullable=True))
        batch_op.alter_column('link_to_plan_document',
               existing_type=sa.VARCHAR(length=999),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('hmo_ppo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('geography',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_document', schema=None) as batch_op:
        batch_op.alter_column('geography',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('hmo_ppo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('link_to_plan_document',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=999),
               existing_nullable=True)
        batch_op.drop_column('summarized_plan_coverage')
        batch_op.drop_column('payer')
        batch_op.drop_column('name_of_plan')

    # ### end Alembic commands ###
